name: TMDC Docker Image CI workflow

on:
  push:
    tags:
      - '*[0-9]+.*[0-9]+.*[0-9]-d*'

env:
  PROJECT_NAME: zookeeper-operator
  EXPORTER_NAME: zookeeper-exporter
  ORG_NAME: rubik-ai
  VERSION: ${{ github.ref_name }}
  GIT_SHA: ${{ github.sha }}


jobs:
# RELEASE STEPS

  release:
    name: Release Build and Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    
    if: startsWith(github.ref, 'refs/tags/') && contains(github.ref, '-d')
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod

    - name: Test Go packages
      run: make test

    - name: Build Go packages
      env:
          REPO: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.PROJECT_NAME }}
      run: make build-go

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and Push operator Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        # cache-from: type=gha
        # cache-to: type=gha,mode=max
        provenance: mode=max
        build-args: |
            DOCKER_REGISTRY=docker.io
            DISTROLESS_DOCKER_REGISTRY=gcr.io
            GIT_SHA=${{ env.GIT_SHA }}
            VERSION=${{ env.VERSION }}
            REPO_PATH=github.com/${{ env.ORG_NAME }}/${{ env.PROJECT_NAME }}
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/zookeeper-operator:${{ github.ref_name }}

    - name: Build and Push zookeeper Docker image
      uses: docker/build-push-action@v6
      with:
        context: docker/
        file: ./docker/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        # cache-from: type=gha
        # cache-to: type=gha,mode=max
        provenance: mode=max
        build-args: |
            DOCKER_REGISTRY=docker.io
            GIT_SHA=${{ env.GIT_SHA }}
            VERSION=${{ env.VERSION }}
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/zookeeper:${{ github.ref_name }}